#! /usr/bin/env php
<?php

use App\Commands\DownloadCommand;
use Dotenv\Dotenv;
use Dotenv\Store\FileStore;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

const DEFAULT_DIR = __DIR__;

// Initialize Dotenv with FileStore
$dotenv = Dotenv::createImmutable(DEFAULT_DIR);
$dotenv->load();

$app = new Application('Codecourse downloader', '2.0');
$app->add(new DownloadCommand());

$app->run();
